author: wragge
description: CollectionBuilder-GH is a template for creating small digital collection
  exhibits on GitHub Pages designed for teaching digital library skills
exclude:
- docs/
- Rakefile
- README.md
- LICENSE
metadata: 83777-items
sass:
  style: compressed
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh
tagline: a template for creating simple digital exhibits
title: Clement Wragge
